### ISSUE TITLE
Log timestamps are not in human readable format

### ISSUE THREAD

**Issue by ameyp** [redhat-cop/vault-config-operator#100]
As far as I can tell, the timestamps are printed in epoch seconds:

```
1.6726932772803226e+09	INFO	secretenginemount-resource	validate update	{"name": "postgresql"}
```

Am I missing a configuration option for printing them in human readable format?

Also, is there a way to set the log level? At present, there are a lot of `DEBUG` logs being printed, I'd like to set mine to print only `INFO` and higher.

**Comment by erlisb** [comment]
afaik, this is not an issue but a default configuration.
In order to enable the requested configurations (timestamp & loglevel), one way to do it would be to add the following command args to the controller-manager container, in the controller-manager Deployment : 

```
      - command:
        - /manager
        args:
        - --leader-elect
        - --zap-time-encoding=iso8601
        - --zap-log-level=debug 
```

To make this generally available, one way would be to extend the helmchart (Deployment template) that is used to deploy the operator i.e : 

```
args:
  - --leader-elect
{{  range .Values.args}}
  - {{ . }}
{{ end }}
```

Additionally, if you just want to use it locally, you can extend the Makefile, as follows : 

```
run: manifests generate fmt vet
	go run ./main.go $(ARGS)

$ make run ARGS="--zap-time-encoding=iso8601" ENABLE_WEBHOOKS=false
```

**Comment by ameyp** [comment]
Nice, ty for the pointers, I'll put out a PR soon

**Comment by ameyp** [comment]
With all these PRs for the helm chart merged, could you bump the version?

**Comment by raffaelespazzoli** [comment]
done: v0.8.5
